config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'hitungsekaligus/index'
  get 'hrgpotong/index'
  get 'totalwaktu/index'
  get 'hrghandling/index'
  get 'dischandling/index'
  get 'berat_material/index'
  get 'keliling/index'
  get 'keliling/bulat'
  get 'keliling/square'
  get 'profile/index'
  get 'default/index'
  resources :customers
  resources :users
  resources :profile
  root :to => 'default#index'
end

app/models/business_entry.rb
class BusinessEntry < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  layout :layout_by_resource
  helper_method :active_section, :active_node

  include ApplicationHelper
  protect_from_forgery

  def index
  	respond_to :html
  end
  protected
    # Root class and active menu items
    def active_section
      @active_section ||= params[:controller]
    end

    def active_node
      @active_node ||= params[:action]
    end

    # System methods
    def not_found
      raise ActionController::RoutingError.new "Not Found"
    end

    def layout_by_resource
      if devise_controller?
        "login"
      else
        "application"
      end
    end
end

app/controllers/berat_material_controller.rb
class BeratMaterialController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/business_entry_controller.rb
class BusinessEntryController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:deleted, :enabled, :name, :contact, :email, :city, :postcode, :phone, :mobile, :fax, :npwp, :npwp_address, :paymentdays, :description)
    end
end

app/controllers/default_controller.rb
class DefaultController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/dischandling_controller.rb
class DischandlingController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/hitungsekaligus_controller.rb
class HitungsekaligusController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/hrghandling_controller.rb
class HrghandlingController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/hrgpotong_controller.rb
class HrgpotongController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/keliling_controller.rb
class KelilingController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

  def bulat
  end

  def square
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/totalwaktu_controller.rb
class TotalwaktuController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_entry_helper.rb
module BusinessEntryHelper
end

app/helpers/hitungsekaligus_helper.rb
module HitungsekaligusHelper
end

app/helpers/hrgpotong_helper.rb
module HrgpotongHelper
end

app/helpers/totalwaktu_helper.rb
module TotalwaktuHelper
end

app/views/berat_material/index.html.erb
<script LANGUAGE="JavaScript">
function cek()
{
  if(form_bm.keliling.value == "" || form_bm.panjang_material.value == "" || form_bm.tebal_material.value == "" || form_bm.berat_jenis.value == "")
  {
    alert("masukkan semua variabel perhitungan");exit;
  }
}
function hitung()
{
  cek();
  kll=eval(form_bm.keliling.value);
  pjm=eval(form_bm.panjang_material.value);
  tbm=eval(form_bm.tebal_material.value);
  bj=eval(form_bm.berat_jenis.value);
  hasil=(kll*pjm*tbm*bj)/1000;
  form_bm.hsl.value = formatCurrency(hasil,"");
}
</script>
<div class="header">
  <h1>Hitung Berat Material</h1>
</div>

<form name="form_bm" accept-charset="UTF-8" class="pure-form">
  <div class="content">
    <div class="pure-g-r">
      <div class="pure-u-1-2">
        <h3>Masukkan Variabel</h3>
        <fieldset>
          <label for="keliling">Keliling</label>
          <input id="keliling" name="keliling" type="number"/>
          <p>Keliling harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="panjang_material">Panjang Material</label>
          <input id="panjang_material" name="panjang_material" type="number"/>
          <p>Panjang material harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="tebal_material">Tebal Material</label>
          <input id="tebal_material" name="tebal_material" type="number"/>
          <p>Tebal material harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="berat_jenis">Berat Jenis</label>
          <input id="berat_jenis" name="berat_jenis" type="number"/>
          <p>Berat jenis harap diisi.</p>
        </fieldset>
      </div>
      <div class="pure-u-1-2">
        <h3 class="">&nbsp;</h3>
        <label for="kll">Berat Material</label>
        <input id="kll" name="hsl" type="text" size="50" class="currency-bulat" readonly="true" />
      </div>
    </div>
    <fieldset class="actions">
      <input class="pure-button pure-button-primary" type=button name=submit onClick="hitung()" value="Hitung">
      <%= link_to '<i class="fa fa-times"></i> Batal'.html_safe, default_index_path %>
    </fieldset>
  </form>
</div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Deleted</th>
      <th>Enabled</th>
      <th>Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>City</th>
      <th>Postcode</th>
      <th>Phone</th>
      <th>Mobile</th>
      <th>Fax</th>
      <th>Npwp</th>
      <th>Npwp address</th>
      <th>Paymentdays</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.deleted %></td>
        <td><%= customer.enabled %></td>
        <td><%= customer.name %></td>
        <td><%= customer.contact %></td>
        <td><%= customer.email %></td>
        <td><%= customer.city %></td>
        <td><%= customer.postcode %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.fax %></td>
        <td><%= customer.npwp %></td>
        <td><%= customer.npwp_address %></td>
        <td><%= customer.paymentdays %></td>
        <td><%= customer.description %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deleted:</strong>
  <%= @customer.deleted %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @customer.enabled %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @customer.contact %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @customer.postcode %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @customer.mobile %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @customer.fax %>
</p>

<p>
  <strong>Npwp:</strong>
  <%= @customer.npwp %>
</p>

<p>
  <strong>Npwp address:</strong>
  <%= @customer.npwp_address %>
</p>

<p>
  <strong>Paymentdays:</strong>
  <%= @customer.paymentdays %>
</p>

<p>
  <strong>Description:</strong>
  <%= @customer.description %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/default/_growl.erb
<% if !flash[:notice].blank? %>
	<span id="flash"><%=flash[:notice]%></span>
<% end %>	
	<div id="growl" class="<%=flash[:type]%>">
		<a class="close">&times;</a>
		<p></p>
	</div>

app/views/default/_link.erb
<%= link_to_if (checkrole "Admin #{title}, User #{title}"), "#{title}" .html_safe,linker do %>
	<span><i class="fa fa-lock"></i><%=title%></span>
<% end %>

app/views/default/_menu.erb
<ul>
	<li>
		<%= link_to 'Keliling', keliling_index_url %>
	</li>
	<li>
		<%= link_to 'Berat Material', berat_material_index_path %>
	</li>
	<li>
		<%= link_to 'Disc.Handling', dischandling_index_path %>
	</li>
	<li>
		<%= link_to 'Harga Handling', hrghandling_index_path %>
	</li>
	<li>
		<%= link_to 'Total Waktu', totalwaktu_index_path %>
	</li>
	<li>
		<%= link_to 'Harga Potong', hrgpotong_index_path %>
	</li>
	<li>
		<%= link_to 'Sekaligus', hitungsekaligus_index_path %>
	</li>
	<li class="buttons menu-item-divided">

		<a href="<%=profile_index_url %>" title="Settings"><i class="fa fa-cog fa-2x" title="Settings"></i></a>
		<%= link_to '<i class="fa fa-sign-out fa-2x"></i>'.html_safe, destroy_user_session_path, :method => :delete, :class => 'tipsy', :title => 'Logout' %>
	</li>
</ul>

app/views/default/index.html.erb
<div class="header">
  <h1>Laser Cutting</h1>
</div>

<%= link_to 'Hitung Keliling', keliling_index_path %><br />
<%= link_to 'Hitung Berat Material', berat_material_index_path %><br />
<%= link_to 'Hitung Disc.Handling', dischandling_index_path %><br />
<%= link_to 'Hitung Harga Handling', hrghandling_index_path %><br />
<%= link_to 'Hitung Total Waktu', totalwaktu_index_path %><br />
<%= link_to 'Hitung Harga Potong', hrgpotong_index_path %><br /><br /><hr /><br />
<%= link_to 'Hitung Sekaligus', hitungsekaligus_index_path %><br />

app/views/dischandling/index.html.erb
<script LANGUAGE="JavaScript">
function cek()
{
  if(form_dh.berat_material.value == "" || form_dh.ljr_materi.value == "")
  {
    alert("masukkan semua variabel perhitungan");exit;
  }
}
function hitung()
{
  cek();
  bm=eval(form_dh.berat_material.value);
  lm=eval(form_dh.ljr_materi.value);
  hasil=bm*lm;
  form_dh.hsl.value = formatCurrency(hasil,"");
}
</script>

<div class="header">
  <h1>Hitung Disc.Handling</h1>
</div>

<form name="form_dh" accept-charset="UTF-8" class="pure-form">
  <div class="content">
    <div class="pure-g-r">
      <div class="pure-u-1-2">
        <h3>Masukkan Variabel</h3>
        <fieldset>
          <label for="berat_material">Berat Material</label>
          <input id="berat_material" name="berat_material" type="number"/>
          <p>Berat material harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="ljr_materi">Kebutuhan Material</label>
          <input id="ljr_materi" name="ljr_materi" type="number"/>
          <p>Kebutuhan material harap diisi.</p>
        </fieldset>
      </div>
      <div class="pure-u-1-2">
        <h3 class="">&nbsp;</h3>
        <label for="kll">Disc.Handling</label>
        <input id="kll" name="hsl" type="text" size="50" class="currency-bulat" readonly="true" />
      </div>
    </div>
    <fieldset class="actions">
      <input class="pure-button pure-button-primary" type=button name=submit onClick="hitung()" value="Hitung">
      <%= link_to '<i class="fa fa-times"></i> Batal'.html_safe, default_index_path %>
    </fieldset>
  </form>
</div>

app/views/hitungsekaligus/index.html.erb
<script LANGUAGE="JavaScript">
var keliling=0;
var hasil=0;
function cek_bangun()
{
  if(form_all.bangun.value == "")
  {
    alert("pilih bangun yang ingin dihitung");exit;
  }
  else if (form_all.bangun.value == "bulat") {
    if(form_all.diameter.value == ""){
      alert("masukkan diameter");exit;
    }
    else{
      keliling =((3.14)*(eval(form_all.diameter.value)));
    }
  }
  else if (form_all.bangun.value == "kotak") {
    if(form_all.panjang.value == "" || form_all.panjang.value == ""){
      alert("masukkan panjang dan lebar bangun");exit;
    }
    else{
      keliling =(((eval(form_all.panjang.value))+(eval(form_all.lebar.value)))*2);
    }
  }
}

function cek_variabel(){
  if(form_all.tebal_material.value == "" || form_all.harga_laser.value == "" || form_all.berat_jenis.value == "" || form_all.material_yang_dibutuhkan.value == "" || form_all.panjang_barang_jadi.value == "" || form_all.harga_handling.value == "" || form_all.cutting_length.value == "" || form_all.cutting_speed.value == "" || form_all.countur.value == "" )
  {
    alert("masukkan variabel yang ingin dihitung");exit;
  }
}

function hitung()
{
  cek_bangun();
  cek_variabel();
  hasil=(
    (((((eval(form_all.cutting_length.value))/(eval(form_all.cutting_speed.value)))+(((eval(form_all.countur.value))*(eval(form_all.tebal_material.value)))/60))/60)*(eval(form_all.harga_laser.value)))+(((eval(form_all.panjang_barang_jadi.value))+(eval(form_all.harga_handling.value)))-
    (((keliling*(eval(form_all.panjang_material.value)))/1000)*(eval(form_all.material_yang_dibutuhkan.value))))
  );
  form_all.harga_potong_laser.value=formatCurrency(hasil,"");
}
</script>
  <div class="header">
    <h1>Hitung Sekaligus</h1>
  </div>

  <form name="form_all" accept-charset="UTF-8" class="pure-form">
    <div class="content">
      <div class="pure-g-r">
        <div class="pure-u-1-2">
          <h3>Masukkan Variabel</h3>
          <fieldset>
            <label for="bangun">Bangun</label>
            <select class="chzn-select" id="bangun" name="bangun">
              <option value="">- Pilih Bangun -</option>
              <option value="bulat"> Bulat </option>
              <option value="kotak"> Kotak </option>
            </select>
            <p>Pilih jenis bangun.</p>
          </fieldset>
          <fieldset>
            <label for="diameter">Diameter</label>
            <input id="diameter" name="diameter" type="number"/>
          </fieldset>
          <fieldset>
            <label for="panjang">Panjang</label>
            <input id="panjang" name="panjang" type="number"/>
          </fieldset>
          <fieldset>
            <label for="lebar">Lebar</label>
            <input id="lebar" name="lebar" type="number"/>
          </fieldset>
          <fieldset>
            <label for="panjang_material">Panjang material</label>
            <input id="panjang_material" name="panjang_material" type="number"/>
            <p>Panjang material harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="tebal_material">Tebal material</label>
            <input id="tebal_material" name="tebal_material" type="number"/>
            <p>Tebal material harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="berat_jenis">Berat jenis</label>
            <input id="berat_jenis" name="berat_jenis" type="number"/>
            <p>Berat jenis harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="material_yang_dibutuhkan">Kebutuhan materi</label>
            <input id="material_yang_dibutuhkan" name="material_yang_dibutuhkan" type="number"/>
            <p>Kebutuhan materi harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="panjang_barang_jadi">Panjang brg.jadi</label>
            <input id="panjang_barang_jadi" name="panjang_barang_jadi" type="number"/>
            <p>Panjang brg.jadi harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="harga_handling">Harga handling</label>
            <input id="harga_handling" name="harga_handling" type="number"/>
            <p>Harga handling harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="cutting_length">Cutting length(m)</label>
            <input id="cutting_length" name="cutting_length" type="number"/>
            <p>Cutting length harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="cutting_speed">Cutting speed</label>
            <input id="cutting_speed" name="cutting_speed" type="number"/>
            <p>Cutting speed harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="countur">Jumlah kontur</label>
            <input id="countur" name="countur" type="number"/>
            <p>Jumlah kontur harap diisi.</p>
          </fieldset>
          <fieldset>
            <label for="harga_laser">Harga laser</label>
            <input id="harga_laser" name="harga_laser" type="number"/>
            <p>Hrg.laser harap diisi.</p>
          </fieldset>
        </div>
        <div class="pure-u-1-2">
          <h3 class="">&nbsp;</h3>
          <fieldset>
            <label for="hsl">Hasil perhitungan</label>
            <input id="hsl" name="harga_potong_laser" type="text" size="50" class="currency-bulat" readonly="true" />
          </fieldset>
        </div>
      </div>
      <fieldset class="actions">
        <input class="pure-button pure-button-primary" type=button name=submit onClick="hitung()" value="Hitung">
        <%= link_to '<i class="fa fa-times"></i> Batal'.html_safe, default_index_path %>
      </fieldset>
    </div>
  </form>

app/views/hrghandling/index.html.erb
<script LANGUAGE="JavaScript">
function cek()
{
  if(form_hh.panjang_barang_jadi.value == "" || form_hh.harga_handling.value == "" || form_hh.dischandling.value == "")
  {
    alert("masukkan semua variabel perhitungan");exit;
  }
}
function hitung()
{
  cek();
  pbj=eval(form_hh.panjang_barang_jadi.value);
  hh=eval(form_hh.harga_handling.value);
  dh=eval(form_hh.dischandling.value);

  hasil=(pbj+hh)-dh;
  form_hh.hsl.value = formatCurrency(hasil,"");
}
</script>
<div class="header">
  <h1>Total Hrg.Handling</h1>
</div>

<form name="form_hh" accept-charset="UTF-8" class="pure-form">
  <div class="content">
    <div class="pure-g-r">
      <div class="pure-u-1-2">
        <h3>Masukkan Variabel</h3>
        <fieldset>
          <label for="panjang_barang_jadi">Panjang brg.jadi</label>
          <input id="panjang_barang_jadi" name="panjang_barang_jadi" type="number"/>
          <p>Panjang brg.jadi harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="harga_handling">Harga handling</label>
          <input id="harga_handling" name="harga_handling" type="number"/>
          <p>Harga handling harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="dischandling">Disc.handling</label>
          <input id="dischandling" name="dischandling" type="number"/>
          <p>Disc.handling harap diisi.</p>
        </fieldset>
      </div>
      <div class="pure-u-1-2">
        <fieldset>
          <h3 class="">&nbsp;</h3>
          <label for="hsl">Total hrg.handling</label>
          <input id="hsl" name="hsl" type="text" size="50" class="currency-bulat" readonly="true" />
        </fieldset>
      </div>
    </div>
    <fieldset class="actions">
      <input class="pure-button pure-button-primary" type=button name=submit onClick="hitung()" value="Hitung">
      <%= link_to '<i class="fa fa-times"></i> Batal'.html_safe, default_index_path %>
    </fieldset>
  </form>
  </div>

app/views/hrgpotong/index.html.erb
<script LANGUAGE="JavaScript">
function cek()
{
  if(form_pl.total_waktu.value == "" || form_pl.harga_laser.value == "")
  {
    alert("masukkan semua variabel perhitungan");exit;
  }
}
function hitung()
{
  cek();
  tw=eval(form_pl.total_waktu.value);
  hl=eval(form_pl.harga_laser.value);
  hasil=(tw/60)*hl;
  form_pl.hsl.value = formatCurrency(hasil,"");
}
</script>
<div class="header">
  <h1>Total Hrg.Potong Laser</h1>
</div>

<form name="form_pl" accept-charset="UTF-8" class="pure-form">
  <div class="content">
    <div class="pure-g-r">
      <div class="pure-u-1-2">
        <h3>Masukkan Variabel</h3>
        <fieldset>
          <label for="total_waktu">Total waktu</label>
          <input id="total_waktu" name="total_waktu" type="number"/>
          <p>Total waktu harap diisi.</p>
        </fieldset>
        <fieldset>
          <label for="harga_laser">Harga laser</label>
          <input id="harga_laser" name="harga_laser" type="number"/>
          <p>Harga laser harap diisi.</p>
        </fieldset>
      </div>
      <div class="pure-u-1-2">
        <h3 class="">&nbsp;</h3>
        <fieldset>
          <label for="hsl">Total hrg.potong laser</label>
          <input id="hsl" name="hsl" type="text" size="50" class="currency-bulat" readonly="true" />
        </fieldset>
      </div>
    </div>
    <fieldset class="actions">
      <input class="pure-button pure-button-primary" type=button name=submit onClick="hitung()" value="Hitung">
      <%= link_to '<i class="fa fa-times"></i> Batal'.html_safe, default_index_path %>
    </fieldset>
  </div>
</form>

app/views/keliling/_nav.html.erb
<ul class="submenu">
  <li<% if where == 'bulat' %> class="on"<% end %>><a href="/keliling/bulat">Bulat</a></li>
  <li<% if where == 'square' %> class="on"<% end %>><a href="/keliling/square">Kotak</a></li>
</ul>

app/views/keliling/index.html.erb
<div class="header">
  <h1>Perhitungan Keliling</h1>
</div>
<%= render "keliling/nav", :where => '' %>

<div class="content">

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Kembali ke Profile', profile_index_path %>